export const AUTH_ENDPOINTS = []

export const AUTH_DATA_STORED_KEY = 'AUTH_DATA'

export const nonAccentedCharactersRegex =
  /[^A-Za-zÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÉÈẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴĐáàảãạăắằẳẵặâấầẩẫậéèẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵ\s]/g
export const numberRegex = /[0-9]/
export const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/
export const onlyEnglishCharacters = /^[a-zA-Z\s]+$/
export const removedAccentMap = {
  Á: 'A',
  À: 'A',
  Ả: 'A',
  Ã: 'A',
  Ạ: 'A',
  Ă: 'A',
  Ắ: 'A',
  Ằ: 'A',
  Ẳ: 'A',
  Ẵ: 'A',
  Ặ: 'A',
  Â: 'A',
  Ấ: 'A',
  Ầ: 'A',
  Ẩ: 'A',
  Ẫ: 'A',
  Ậ: 'A',
  É: 'E',
  È: 'E',
  Ẻ: 'E',
  Ẽ: 'E',
  Ẹ: 'E',
  Ê: 'E',
  Ế: 'E',
  Ề: 'E',
  Ể: 'E',
  Ễ: 'E',
  Ệ: 'E',
  Í: 'I',
  Ì: 'I',
  Ỉ: 'I',
  Ĩ: 'I',
  Ị: 'I',
  Ó: 'O',
  Ò: 'O',
  Ỏ: 'O',
  Õ: 'O',
  Ọ: 'O',
  Ô: 'O',
  Ố: 'O',
  Ồ: 'O',
  Ổ: 'O',
  Ỗ: 'O',
  Ộ: 'O',
  Ơ: 'O',
  Ớ: 'O',
  Ờ: 'O',
  Ở: 'O',
  Ỡ: 'O',
  Ợ: 'O',
  Ú: 'U',
  Ù: 'U',
  Ủ: 'U',
  Ũ: 'U',
  Ụ: 'U',
  Ư: 'U',
  Ứ: 'U',
  Ừ: 'U',
  Ử: 'U',
  Ữ: 'U',
  Ự: 'U',
  Ý: 'Y',
  Ỳ: 'Y',
  Ỷ: 'Y',
  Ỹ: 'Y',
  Ỵ: 'Y',
  Đ: 'D',
  á: 'a',
  à: 'a',
  ả: 'a',
  ã: 'a',
  ạ: 'a',
  ă: 'a',
  ắ: 'a',
  ằ: 'a',
  ẳ: 'a',
  ẵ: 'a',
  ặ: 'a',
  â: 'a',
  ấ: 'a',
  ầ: 'a',
  ẩ: 'a',
  ẫ: 'a',
  ậ: 'a',
  é: 'e',
  è: 'e',
  ẻ: 'e',
  ẽ: 'e',
  ẹ: 'e',
  ê: 'e',
  ế: 'e',
  ề: 'e',
  ể: 'e',
  ễ: 'e',
  ệ: 'e',
  í: 'i',
  ì: 'i',
  ỉ: 'i',
  ĩ: 'i',
  ị: 'i',
  ó: 'o',
  ò: 'o',
  ỏ: 'o',
  õ: 'o',
  ọ: 'o',
  ô: 'o',
  ố: 'o',
  ồ: 'o',
  ổ: 'o',
  ỗ: 'o',
  ộ: 'o',
  ơ: 'o',
  ớ: 'o',
  ờ: 'o',
  ở: 'o',
  ỡ: 'o',
  ợ: 'o',
  ú: 'u',
  ù: 'u',
  ủ: 'u',
  ũ: 'u',
  ụ: 'u',
  ư: 'u',
  ứ: 'u',
  ừ: 'u',
  ử: 'u',
  ữ: 'u',
  ự: 'u',
  ý: 'y',
  ỳ: 'y',
  ỷ: 'y',
  ỹ: 'y',
  ỵ: 'y',
  đ: 'd',
}

// COA Account Status Configuration
export const STATUS_ACCOUNT = [
  {
    status: "Active",
    statusBg: "bg-[#e4f6d2]",
    statusColor: "text-[#07564d]",
    statusHover: "hover:bg-[#e4f6d2]",
  },
  {
    status: "Lock",
    statusBg: "bg-[#f7e1e1]",
    statusColor: "text-[#641d1a]",
    statusHover: "hover:bg-[#f7e1e1]",
  },
  {
    status: "Inactive",
    statusBg: "bg-[#efefef]",
    statusColor: "text-[#000000b2]",
    statusHover: "hover:bg-[#efefef]",
  }
] as const;

// COA Account Type Configuration
export const TYPES_ACCOUNT = [
  {
    type: "Asset",
    typeBg: "bg-[#e4f6d2]",
    typeColor: "text-[#07564d]",
    typeHover: "hover:bg-[#e4f6d2]",
  },
  {
    type: "Equity",
    typeBg: "bg-[#fff1df]",
    typeColor: "text-[#d2510e]",
    typeHover: "hover:bg-[#fff1df]",
  },
  {
    type: "Exp",
    typeBg: "bg-[#daedff]",
    typeColor: "text-[#192e53]",
    typeHover: "hover:bg-[#daedff]",
  },
  {
    type: "Liab",
    typeBg: "bg-[#f7e1e1]",
    typeColor: "text-[#641d1a]",
    typeHover: "hover:bg-[#f7e1e1]",
  },
  {
    type: "Rev",
    typeBg: "bg-[#efefef]",
    typeColor: "text-[#000000b2]",
    typeHover: "hover:bg-[#efefef]",
  }
] as const;